import prisma from '../../db';
import { callAI, buildUserContext } from '../ai/aiService';
import { z } from 'zod';

export async function runStreakProtectionCheck(userId: string) {
  // 1. Check user's streak
  const user = await prisma.user.findUnique({ where: { id: userId } });
  if (!user || user.currentStreak <= 0) return { status: 'ignored', reason: 'No active streak' };

  // 2. Check if user has logged a workout today
  const startOfDay = new Date();
  startOfDay.setHours(0, 0, 0, 0);

  const workoutsToday = await prisma.workoutSession.count({
    where: {
      userId,
      createdAt: { gte: startOfDay }
    }
  });

  if (workoutsToday > 0) return { status: 'safe', reason: 'Workout already logged today' };

  // 3. User is at risk! Generate a 5-minute Micro-Workout via AI
  const userContext = await buildUserContext(userId);
  const schema = z.object({
    exercises: z.array(z.object({
      name: z.string(),
      muscleGroup: z.string(),
      sets: z.number(),
      reps: z.number(),
      weight: z.string(),
      restTime: z.number()
    }))
  });

  const aiResult = await callAI({
    system: `You are Rachel, an AI fitness coach. The user's streak is at risk. 
Generate a fast, 5-minute, equipment-free micro-workout tailored to their profile and avoiding any high-risk recovery areas.
Return exactly 3 exercises.`,
    prompt: `Context: ${JSON.stringify(userContext)}`,
    schema
  });

  const exercises = aiResult.ok && aiResult.data ? aiResult.data.exercises : [
    { name: 'Bodyweight Squats', muscleGroup: 'Legs', sets: 2, reps: 15, weight: 'Bodyweight', restTime: 30 },
    { name: 'Pushups', muscleGroup: 'Chest', sets: 2, reps: 10, weight: 'Bodyweight', restTime: 30 },
    { name: 'Plank', muscleGroup: 'Core', sets: 2, reps: 60, weight: 'Seconds', restTime: 30 }
  ];

  const microWorkout = await prisma.workout.create({
    data: {
      userId,
      title: 'Streak Saver: 5-Min Flow',
      duration: '5',
      aiExplanation: 'Generated by Rachel to protect your streak!',
      isCurrent: true,
      exercises: {
        create: exercises.map((e: any, i: number) => ({
          name: e.name,
          muscleGroup: e.muscleGroup,
          sets: e.sets,
          reps: e.reps,
          weight: e.weight,
          restTime: e.restTime,
          order: i,
          status: 'pending'
        }))
      }
    },
    include: { exercises: true }
  });

  // 4. Send a Coach Message to notify them
  await prisma.coachMessage.create({
    data: {
      userId,
      role: 'Rachel',
      content: 'Hey! I noticed you haven\'t logged a workout today and your streak is at risk. I just generated a 5-minute Streak Saver flow for you. Just do it in your living room!'
    }
  });

  return { status: 'triggered', workout: microWorkout };
}
