import prisma from '../../db';

export async function runStreakProtectionCheck(userId: string) {
  // 1. Check user's streak
  const user = await prisma.user.findUnique({ where: { id: userId } });
  if (!user || user.currentStreak <= 0) return { status: 'ignored', reason: 'No active streak' };

  // 2. Check if user has logged a workout today
  const startOfDay = new Date();
  startOfDay.setHours(0, 0, 0, 0);

  const workoutsToday = await prisma.workout.count({
    where: {
      userId,
      createdAt: { gte: startOfDay },
      deletedAt: null
    }
  });

  if (workoutsToday > 0) return { status: 'safe', reason: 'Workout already logged today' };

  // 3. User is at risk! Generate a 5-minute Micro-Workout to save the streak
  const microWorkout = await prisma.workout.create({
    data: {
      userId,
      title: 'Streak Saver: 5-Min Flow',
      duration: '5 min',
      aiExplanation: 'Generated by Rachel to protect your streak!',
      exercises: {
        create: [
          { name: 'Bodyweight Squats', sets: 2, reps: 15, weight: 'Bodyweight' },
          { name: 'Pushups', sets: 2, reps: 10, weight: 'Bodyweight' },
          { name: 'Plank', sets: 2, reps: 60, weight: 'Seconds' }
        ]
      }
    },
    include: { exercises: true }
  });

  // 4. Send a Coach Message to notify them
  await prisma.coachMessage.create({
    data: {
      userId,
      role: 'Rachel',
      content: 'Hey! I noticed you haven\'t logged a workout today and your streak is at risk. I just generated a 5-minute Streak Saver flow for you. Just do it in your living room!'
    }
  });

  return { status: 'triggered', workout: microWorkout };
}
